valueflows/valueflows

README.md

Adding the REA citation and links

Yet another readme improvement

---

PRINCIPLES.md

i prefer we have this in our main repo as opposed to wiki, so any changes are obvious.
part of https://github.com/valueflows/valueflows/issues/43

add principles from wiki to PRINCIPLES.md

---

use-cases/colab.md
use-cases/enspiral.md

- CoLab services
- Enspiral services

migrate use cases from wiki to `use-cases/`

---

CONTRIBUTING.md

stolen from [holodex](https://github.com/open-app/holodex/blob/master/CONTRIBUTING.md), [node](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md), and https://github.com/valueflows/valueflows/issues/41#issuecomment-146548933.
feedback appreciated! :cat:

first pass at CONTRIBUTING.md

---

context.jsonld

first pull request towards https://github.com/valueflows/valueflows/issues/34.
changes:
- remove special handling of `rdfs:label`
- add `label` which points to `skos:prefLabel`
- add `labelMap` which is language map for `label`
- add `note` which points to `skos:note`
- add `noteMap` which is language map for `note`
- remove `displayName` and `displayNameMap`
- `Relationship` is also a `skos:Concept`

use skos label and note

---

AUTHORS

such contributions, very awesome, thanks. :cake:
is being added to the authors list okay with you @pmackay?

add @pmackay to AUTHORS

---

release-doc-in-process/all_vf.TTL

I made some changes to the ttl, haven't regenerated the VOWL diagram or tested.  Please review, especially @elf-pavlik .
The fulfillment stuff is not completely fixed, we need to review all of that some time.  Probably other things to fix too.
(InputOutput is an old name for Event.)

eliminate InputOutput, add action verbs, other tweaks

---

release-doc-in-process/all_vf.TTL

based on discussion in #185 
please pay attention to possibly confusing git diff, maybe i shouldn't have changed order of definition and edit it at the same time... you can always View version of the file in this PR without the diff.

changed Templates to TaxonomyItems

---

PRINCIPLES.md

... to include principle towards supporting different organizational forms and experimentation.  Please let me know if you agree with that for VF.

Updated #7

---

docs/specification/classes/resource.md

I'm making the change just in this file.  If accepted, I'll make it elsewhere in the docs.
Note I also got rid of the text, which now occurs elsewhere.

Change name to EconomicResource

---

docs/specification/classes/event.md

Made that change just here, if accepted, I'll fix it everywhere it occurs.
(Also got rid of the text in this file, because it is now elsewhere.  Hoping to generate these eventually.)

change name to EconomicEvent

---

release-doc-in-process/all_vf.TTL

@elf-pavlik and I think this one could be 0.1.... :)  Objections?

fixes to action verbs

---

docs/appendix/overview.md

Ecosystemic and agent-based algos added to overview

More Algorithms

---

json-schemas/EconomicEvent.json
json-schemas/EconomicResource.json

Will continue, and iterate as needed per feedback.

First json-schemas, with some ??s.

---

json-schemas/Agent.json
json-schemas/AgentRelationship.json
json-schemas/EconomicResource.json

Fix to resource, added agent and relationship.

Json schemas

---

json-schemas/EconomicResource.json
json-schemas/Process.json
json-schemas/sample-process-flow.json

Created simple process flow example, not syntactically checked.
Also dialed back the json-schema temporarily so currentLocation and resourceClassifiedBy are just strings, for simple observation layer example to try in ssb.

created simple process flow example

---

docs/introduction/exchanges.md

Clarify text on exchange after a discussion with someone who wondered about gift economy.

add non-reciprocal transfers

---

docs/SUMMARY.md
docs/introduction/scoping.md
release-doc-in-process/all_vf.TTL

generalized scoping

---

release-doc-in-process/all_vf.TTL

simpified classifications

---

docs/appendix/track.md
docs/introduction/concepts.md

Capturing input from @bhaugen from issues and discussion, to start documentation on traversing resource flows.  This will need to be further developed as we nail down any changes/additions to transfer under development.

starting documentation of traversing value flows

---

release-doc-in-process/all_vf.TTL

Once merged I will remove those parts from #302

Intent related changes extracted from Proposal PR

---

release-doc-in-process/all_vf.TTL

remove inverse properties

---

release-doc-in-process/all_vf.TTL

Ttl tweaks

---

package.json
release-doc-in-process/all_vf.TTL

give all terms initial *unstable* status

---

CONTRIBUTING.md

added minimal guidelines on term status advancment and writing snippets

---

examples/process-workflow-examples.yaml

moved process workflow example to create separate PR

Simple examples: process (workflow)

---

examples/fulfill-satisfy-example.yaml

intent-satisfaction-commitment-fulfillment-event

first cut flows example

---

.gitignore
.scripts/convert.js
.scripts/deploy.sh
.travis.yml
package.json

work in progress, still checking how it works on TravisCI

minimal replacement of lod-converter

---

docs/specification/external-terms.md
release-doc-in-process/all_vf.TTL

`rdfs:range skos:note` doesn't make any sense, we should simply use `skos:note` directly

external terms

---

docs/introduction/status.md

DO NOT MERGE YET!!
I started updating the status page for the next release.  Mostly I wanted to explore how to think about the state of this vocabulary, how stable is it / can it be / do we want it to be, in general and in the next release in particular.  Discussion of this question would be welcome!

Explaining general status of the model/vocab.

---

release-doc-in-process/all_vf.TTL

define better later (we have been looking at several different quantities in Intents)

added intended qty

---

docs/SUMMARY.md
docs/introduction/contributors.md

Contributors

---

docs/introduction/contributors.md

added to contribs

---

docs/introduction/resources.md

Saw this when working on other stuff...

Minor updates on resource text.

---

docs/introduction/resources.md

(has been asked by 2 people in the last week)

clarify resource classification and specification

---

examples/process-manufacturing.yaml
examples/process-workflow.yaml
release-doc-in-process/all_vf.TTL

I think we agree on this, so I thought I'd get that pushed.

change affects to involves for events

---

examples/process-manufacturing.yaml
examples/process-workflow.yaml

follow on to changing the name in the ttl
(we'll have to review other examples as things start to get merged to bring up to date)

fix resourceInventoriedAs in merged examples

---

docs/SUMMARY.md
docs/introduction/exchanges.md
docs/introduction/transfers.md

This can be updated more when we get transfers figured out.  But I thought in the meantime, we could add clarity by separating this out.

separate exchange and transfer pages

---

docs/introduction/exchanges.md

In this paragraph I intend to explain that exchanges do not have to happen exclusively between two agents. VF supports multilateral exchange agreements and one between two agents comes as common special case of more general multilateral agreements.

introduce multilateral exchange agreements

---

release-doc-in-process/all_vf.TTL

couple of definitions plus missing property

filled in missing claim info

---

docs/introduction/resources.md
release-doc-in-process/all_vf.TTL

Changing direction of contains relationship to match everything else we have.  Also fixed one typo randomly.

contains > containedIn

---

examples/claim.yaml
examples/exch-agreement.yaml
examples/fulfill-satisfy.yaml
examples/process-manufacturing.yaml
examples/process-workflow.yaml
release-doc-in-process/all_vf.TTL

Using flowQuantity for the quantities on the flows.  For this release until quantity discussions resolved.

flowQuantity (for now)

---

docs/SUMMARY.md
docs/introduction/agents.md
docs/introduction/flows.md
docs/introduction/processes.md
docs/introduction/resources.md
docs/introduction/scoping.md
examples/claim.yaml
examples/ex-agent.md
examples/ex-complex.md
examples/ex-exchange.md
examples/ex-planning.md
examples/ex-production.md
examples/ex-resource.md
examples/fulfill-satisfy.yaml
examples/process-manufacturing.yaml
examples/simple-plan.yaml

There is  a bunch more work to be done after merging this, but this will be helpful to see how it works technically and user experience.  I'll continue to work on it after merging.

first cut example section

---

docs/SUMMARY.md

changed to new LODE generated spec

---

LICENSE.md
README.md
docs/README.md
docs/specification/diagrams/uml.md

Also a note about making the uml diagram bigger in the display.

Added CC-BY-SA license.  

---

release-doc-in-process/all_vf.TTL

Added long, lat, alt, created - to define domain or range.
@jvanbockryck it is OK to define the range as double for an AnnotationProperty, I assume?

long, lat, alt, created

---

examples/agent.yaml
release-doc-in-process/all_vf.TTL

Fixed up labels, added hard-coded behaviors (the AgentRelationhipRoles are user-definable).  The behavior individuals are definitely a first cut.  Feedback welcome!  Noting that the individuals can be added to later; the more important thing now is the data structure.

First cut agent role enhancements.

---

release-doc-in-process/all_vf.TTL

Action no longer a subclass of Property, so we can have configuration / metadata kinds of information for each action, which is now defined as a NamedIndividual.
I think the examples work as they are.

Defined Actions as individuals, added configuration properties.

---

release-doc-in-process/all_vf.TTL

* name, image, uri rounded out to be more complete
* lot and trackingIdentifier type fixed
* skos:Note added to define domain
* prefix fixes discovered in protege
@jvanbockryck can you review this please?

fixes and completions

---

docs/specification/external-terms.md
examples/budget.yaml
examples/checkout-book.yaml
examples/claim.yaml
examples/exch-agreement.yaml
examples/exch-retail.yaml
examples/fulfill-satisfy.yaml
examples/move-crypto.yaml
examples/plan-from-recipe.yaml
examples/process-manufacturing.yaml
examples/process-service.yaml
examples/process-workflow.yaml
examples/proposal-barter.yaml
examples/proposal-list.yaml
examples/proposal-plan.yaml
examples/resource.yaml
examples/simple-plan.yaml
examples/simple-proposals.yaml
examples/transfer-crypto.yaml
examples/transport-with-transfer.yaml
examples/workflow-stage-state.yaml
release-doc-in-process/all_vf.TTL

First cut replacement.  Please don't merge yet, I need to validate all the yaml examples.  But please do review! @jvanbockryck @bhaugen

replace qudt with om2

---

docs/specification/external-terms.md
release-doc-in-process/all_vf.TTL

external doc, notApplicable for pairsWith

small fixes

---

docs/SUMMARY.md
docs/introduction/flows.md
docs/specification/external-terms.md

external links; added column for flows table to separate out "accounting affect" and "onhand affect" for actions affect on resources.

doc improvements

---

docs/introduction/flows.md
examples/claim.yaml
examples/exch-agreement.yaml
examples/exch-retail.yaml
examples/proposal-barter.yaml
examples/proposal-list.yaml
examples/proposal-plan.yaml
examples/simple-proposals.yaml
examples/transfer-crypto.yaml
examples/transport-with-transfer.yaml
release-doc-in-process/all_vf.TTL

Change name of `transfer-complete` to `transfer`.  Timing should be determined by @pospi , and I can do the vf-graphql too.  (See https://github.com/valueflows/valueflows/issues/606.)

transfer-complete > transfer

---

release-doc-in-process/all_vf.TTL

Ref. https://github.com/valueflows/valueflows/issues/615#issuecomment-613091091
Actually, I like this solution a lot better now that I have realized we only want a few actions included.  So thanks @orthecreedence !

add PairsWith as a class, include some actions

---

examples/transport-with-transfer.yaml

missing line in example found by @fkleedorfer thanks!!

fix transport example

---

release-doc-in-process/all_vf.TTL

Redoing this PR without the UML diagram changes, will do those next.

redo - add default units of effort and resource

---

CHANGELOG.md
docs/introduction/status.md
release-doc-in-process/all_vf.TTL

Change log, other updates for creating V 0.5.

Doc for version 0.5.
