valueflows/valueflows

context.jsonld
we're using it in our examples of relationships, as well as our prototype apps, so here's a proposal to add it to our `@context`.
relevant discussion: https://github.com/valueflows/valueflows/issues/52.
=> add `inverseOf` to context

release-doc-in-process/all_vf.TTL
this aligns the definitions with https://www.w3.org/TR/activitystreams-vocabulary/#dfn-relationship
we can eventually reuse AS2.0 terms once it becomes REC
=> remove RelationshipTemplate

release-doc-in-process/all_vf.TTL
this PR IMO simplifies Input/Output relationships between Processes and Intents/Commitments/Events
Instead of relying on interpretation of 'action verb' the which relates Intent/Commitment/Event to a Process itself captures the input/output aspect.
Since we consider defining service as Intent/Commitment/Event which can reference two processes
* one as *outputOf*
* other as *inputOf*
Approach below makes it possible, since in case where we need to relatet I/C/E to two processes we can't just rely on 'action verb'.
Not sure if we need distinct properties for Intent, Commitment and Event or enough to just have *inputOf* & *outputOf* and rely on the type of instance using them to make distinction between Intent, Commitment and Event expressing Inputs and Outputs.
=> clearer I/O relation between Process and I/C/E

json-schemas/sample-create-resource.json
including new resource data on the resource on the event... but no reference to an id of the resource, thinking this could be a way to indicate a new resource rather than affecting an existing resource.... (all experimental)
=> example json event to create resource

release-doc-in-process/all_vf.TTL
Wanting to get this done before creating the webvowl pictures.
Reason for the property is you can never tell if intents/commitments/processes are finished by looking at what was actually done, they need to be explicitly marked as such.  Important filter so UI can display only open activity.
=> add finished to the ttl

release-doc-in-process/all_vf.TTL
I think we will be changing this in some way soon.  Given the statement that nobody can make a commitment except the person committing - but a "claim" or a vf:Reciprocity is modeled now so that it requires the commitment (associative entity, reified entity).  So I think we agree that claim != commitment.  So we need to re-think this structure.  Can do after this release.
=> removed vf:Reciprocity for now

.scripts/convert.js
it just adds two more serializations of the vocab that one can content negotiate on https://w3id.org/valueflows
=> added trig and n-quads represenations

docs/specification/external-terms.md, examples/fulfill-satisfy.yaml, examples/process-workflow.yaml, release-doc-in-process/all_vf.TTL
This reduces one level of indirection and duplication in the vocab. We can simply consider any `Intent`, `Commitment` and `EconomicEvent` as more specific `time:TemporalEntity` and use properties defined in [Time Ontology in OWL](https://www.w3.org/TR/owl-time/#namespaces) directly one them. Since we already have distinct `Intent`, `Commitment` and `EconomicEvent` we don't need in addition `observed*`, `commited*` and `intended*` prefixes. One can simply check `rdf:type` (`@type`) of flow to have that knowledge.
Our examples already incorrectly use `time:intervalEnds` and `time:intervalStarts` (which have `time:ProperInterval` as range) we have to update them to `time:hasBeggining` and `time:hasEnd` (which have `time:Instant` as range). If we accept this PR, we can use those properties …
=> improve integration with OWL-Time

release-doc-in-process/all_vf.TTL
made the Process.duration more specific, limiting the fields that people would use a bit - unitType, numericDuration
ref. https://www.w3.org/TR/owl-time/#duration
=> TemporalDuration > Duration

release-doc-in-process/all_vf.TTL
involves > resourceInventoriedAs in the flows
much clearer name, and also groups better conceptually with resourceClassifiedAs and resourceConformsTo, clarifying these together give you what is known about the little-r resource
[edit If there is agreement, I'll also change the existing examples and add here, or do as a separate PR right away]
=> changing name of involves

docs/introduction/flows.md, examples/claim.yaml, release-doc-in-process/all_vf.TTL
@elf-pavlik @bhaugen 
This is to replace the removed Reciprocity, which created Commitments from Economic Events.  It was observed that Claims are different than Commitments because commitments can only be committed by the provider, while claims are initiated by the hopeful receiver.
Model looks like this.  Claim has most of the properties of I-C-E- flows.  Claim basically references both the event(s) that triggered the claim and the event(s) that resolve the claim.  [edit: WRONG model, see following comments]
I included a brief description in the flows page.  Probably a lot more could be said eventually.
The terms are straight out of McCarthy / REA.  
Note REA people also talk about claims and 'negative claims'.  Negative claims are things like issuing dividends.  I haven't defined those …
=> claim model

examples/exch-agreement.yaml, release-doc-in-process/all_vf.TTL
Recreated from https://github.com/valueflows/valueflows/pull/421.  Basically this adds relationships between Agreement and Commitment / EconomicEvent for agreements that are defined in VF.  Got rid of subclasses of agreement.  I'll close the old one.
=> recreate agreement relationships

release-doc-in-process/all_vf.TTL
Added observedLocation to EconomicEvent, per discussion https://github.com/valueflows/valueflows/issues/486.  Also put vf:Location back for now.  We can swap in another vocab for this if we want.  I'll add a few property references from other vocabs, unless you get there first @elf-pavlik .
=> added observedLocation, put other Location refs back

release-doc-in-process/all_vf.TTL
Since we got rid of ExchangeAgreement, I'm seeing a need to differentiate the agreements which are part of VF, and will be created along with commitments, etc. and agreements which are just referenced and will not be defined or created as part of VF.  This removes agreements referenced by vf:under from VF.
Also took vf:under off of Fulfillment, probably not needed there, leaving on all the flows.
=> range of vf:under, removed fulfillment ref

docs/introduction/resources.md, release-doc-in-process/all_vf.TTL
I think this clarifies the resource classification and resource specification difference.  I got this idea from reading some of McCarthy's recent writings.  This seems a lot cleaner conceptually than something sort of like "it is on the web or it is either part of a recipe or not on the web".  From his doc:
* typify - the association between a concrete entity and the abstract specification of its essential and computed properties.  Typifying a concrete object, person, or occurrence attempts to specify properties that capture its archetypal essence.  This definition derives from Platonic philosophy.
* group - the association between a concrete entity and another concrete class that defines its aggregated and computed properties.  Typing and grouping are abstraction mechanisms that at the …
=> clarify resource spec vs classif

release-doc-in-process/all_vf.TTL
Discussion here: https://github.com/valueflows/valueflows/issues/521.
Pulled out both ResourceSpecification and new ProcessSpecification from the recipe, to support them being in different modules in VF apps.  And in modeling terms to separate the concerns of the specifications and the recipe anyhow, just exposed by the app modularization work.
=> separated out specifications from recipe

docs/SUMMARY.md, docs/specification/json-schema-ref.md, docs/specification/protege-spec.md
Removed page to show json-schemas, can return to when more time.  Linking to the json-schema repo instead.
=> Json schema using repo

release-doc-in-process/all_vf.TTL
Thanks to @pospi for questioning this, these are in any case derivable, but keeping them on EconomicResource and removing from recipe/planning seems right.  @bhaugen please review.
=> removed state/stage from recipeflow and commitment

release-doc-in-process/all_vf.TTL
Added accounting agent to the resource.  This is "owner" and whatever owner becomes in a less owner-oriented economic system, so I'm avoiding the term.  It is the agent that includes the resource in their accounting reports or UI as part of their inventory. 
Looking for the best name, suggestions welcome.  I have it as primaryAccountable.  Have also toyed with primaryAccounting, primaryResponsible.  Thought I had a better name earlier in discussion with @jvanbockryck but can't find it now.
This is a simple version of agent-resource relationships, user defined, such as we have used in NRP/OCP.  Right now I don't think we want that whole mechanism.  If we add something like that later, this will still be useful as a direct filter on resources.
=> adding resource primary agent

release-doc-in-process/all_vf.TTL
Quick edit for something I found while generating the Rust classes. I think this ref to `vf:Agent` shoudl be `foaf:Agent`. Thanks!
=> fix ref from vf:Agent -> foaf:Agent
